backend:
  name: github
  repo: chkuhlmann/chk-site  # Path to your blog repo
  branch: main                               # The branch your site builds from
  base_url: https://decap-proxy.deadrainbow.workers.dev # Your Worker URL
  auth_endpoint: auth                        # Tells Decap to use the worker's auth route

media_folder: "images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Category", name: "category", widget: "string", default: "General"}
      - {label: "Body", name: "body", widget: "markdown"}